@app_HostAddress = http://localhost:5180

GET {{app_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{app_HostAddress}}/api/hello/world

###
GET {{app_HostAddress}}/api/user

###
POST {{app_HostAddress}}/api/user
Content-Type: application/json

{
  "name": "Luiz",
  "email": "luiz@email.com"
}

###
@userId = fa69091a-cc81-43c9-8fc5-a1f6a0190ad6
GET {{app_HostAddress}}/api/user/{{userId}}

###
DELETE {{app_HostAddress}}/api/user/{{userId}}

###
POST {{app_HostAddress}}/api/user/{{userId}}/vehicles
Content-Type: application/json

{
  "model": "Honda Civic Touring 2020 Flex 1.5 Turbo",
  "license_plate": "ABC-1234"
}